{{ if .Values.service.jenkins_runner }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}jenkins-runner
  labels:
    app.service: {{ .Values.prefix }}jenkins-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ .Values.prefix }}jenkins-runner
  template:
    metadata:
      labels:
        app.service: {{ .Values.prefix }}jenkins-runner
    spec:
      containers:
      - env:
        {{- range $key, $value := .Values.docker.services.php_base.environment }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.docker.services.jenkins_runner.environment }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.environment }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        image: {{ .Values.docker.image.jenkins_runner }}
        imagePullPolicy: Always
        name: jenkins-runner
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory.jenkins_runner }}
          requests:
            memory: {{ .Values.resources.requests.memory.jenkins_runner }}
        readinessProbe:
          exec:
            command:
            - app
            - state
          initialDelaySeconds: 20
          periodSeconds: 10
      imagePullSecrets:
      - name: {{ .Values.prefix }}docker-config
      restartPolicy: Always
status: {}
{{ end }}
